# CatBoost

## Importing the libraries

In [ ]:
!pip install catboost

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

## Importing the dataset

In [43]:
dataset = pd.read_csv('Track_1 - Copy.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
y=y-1

In [44]:
dataset1 = pd.read_csv('testing_data.csv')
lopa = dataset1.iloc[:, :].values

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0,1,2,3,4,5,6,7,8,9,10,11,12])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X[0]

## Splitting the dataset into the Training set and Test set

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [ ]:
print(X_train)

In [45]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=4096, activation='relu'))
ann.add(tf.keras.layers.Dropout(0.2))
ann.add(tf.keras.layers.Dense(units=256, activation='relu'))
ann.add(tf.keras.layers.Dropout(0.2))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
X_train = np.asarray(X_train).astype('float32')
X_test = np.asarray(X_test).astype('float32')
y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [47]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics='accuracy')

In [48]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
22/22 [==============================] - 1s 15ms/step - loss: 0.2377 - accuracy: 0.6229
Epoch 2/100
22/22 [==============================] - 0s 15ms/step - loss: 0.1982 - accuracy: 0.6943
Epoch 3/100
22/22 [==============================] - 0s 14ms/step - loss: 0.1910 - accuracy: 0.7143
Epoch 4/100
22/22 [==============================] - 0s 15ms/step - loss: 0.1786 - accuracy: 0.7400
Epoch 5/100
22/22 [==============================] - 0s 15ms/step - loss: 0.1767 - accuracy: 0.7443
Epoch 6/100
22/22 [==============================] - 0s 15ms/step - loss: 0.1593 - accuracy: 0.7557
Epoch 7/100
22/22 [==============================] - 0s 14ms/step - loss: 0.1491 - accuracy: 0.7771
Epoch 8/100
22/22 [==============================] - 0s 16ms/step - loss: 0.1549 - accuracy: 0.7771
Epoch 9/100
22/22 [==============================] - 0s 14ms/step - loss: 0.1419 - accuracy: 0.8000
Epoch 10/100
22/22 [==============================] - 0s 17ms/step - loss: 0.1327 - accuracy: 0.8229

In [49]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=8)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

3/3 [==============================] - 0s 5ms/step
[[1.38383029e-06 0.00000000e+00]
 [6.12682216e-02 0.00000000e+00]
 [1.31022800e-02 0.00000000e+00]
 [5.56438172e-05 0.00000000e+00]
 [3.20943967e-02 1.00000000e+00]
 [9.16703999e-01 1.00000000e+00]
 [3.69914435e-03 0.00000000e+00]
 [9.99236524e-01 1.00000000e+00]
 [9.81452882e-01 1.00000000e+00]
 [4.27357346e-01 0.00000000e+00]
 [8.67253959e-01 0.00000000e+00]
 [9.98998284e-01 1.00000000e+00]
 [7.35187590e-01 1.00000000e+00]
 [9.99397814e-01 1.00000000e+00]
 [1.91491374e-04 0.00000000e+00]
 [6.26318693e-01 1.00000000e+00]
 [2.91926056e-01 0.00000000e+00]
 [3.44813138e-01 0.00000000e+00]
 [2.63438839e-02 0.00000000e+00]
 [4.01573834e-06 0.00000000e+00]
 [2.17145923e-09 0.00000000e+00]
 [9.99919832e-01 1.00000000e+00]
 [3.43562956e-10 0.00000000e+00]
 [3.77570848e-12 0.00000000e+00]
 [2.94891914e-04 0.00000000e+00]
 [9.36639309e-01 0.00000000e+00]
 [8.96405518e-01 0.00000000e+00]
 [8.60485375e-01 1.00000000e+00]
 [6.94092214e-02 0.000000

In [41]:
y_pred_1 = ann.predict(X_train)

20/20 [==============================] - 0s 4ms/step


In [21]:
y_pred_2 = ann.predict(lopa)

13/13 [==============================] - 0s 4ms/step


In [ ]:
print(y_pred)

## Training CatBoost on the Training set

In [ ]:
from catboost import CatBoostClassifier
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)

In [ ]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_train, y_pred_1)
print(cm)
accuracy_score(y_train, y_pred_1)

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[32  8]
 [ 3 35]]


0.8589743589743589

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

In [ ]:
X.pop(0)

In [ ]:
np.shape(y_pred)

(78, 1)

In [ ]:
# build the lightgbm model
import lightgbm as lgb
clf = lgb.LGBMClassifier()
clf.fit(X_train, y_train)

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))
ann.fit(X_train,Y_train,batch_size=32,epochs = 100)ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))
ann.fit(X_train,Y_train,batch_size=32,epochs = 100)

## Making the Confusion Matrix

## Applying k-Fold Cross Validation

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [50]:
for i in range (0,78):
  if y_pred[i][0]>0.5:
    y_pred[i][0]=1
  else:
    y_pred[i][0]=0

In [35]:
for i in range (0,156):
  if y_pred[i][0]>0.5:
    y_pred[i][0]=1
  else:
    y_pred[i][0]=0

In [36]:
y_pred

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],

In [15]:
for i in range (0,700):
  if y_pred_1[i][0]>0.5:
    y_pred_1[i][0]=1
  else:
    y_pred_1[i][0]=0

In [40]:
for i in range (0,624):
  if y_pred_1[i][0]>0.5:
    y_pred_1[i][0]=1
  else:
    y_pred_1[i][0]=0

In [22]:
for i in range (0,400):
  if y_pred_2[i][0]>0.5:
    y_pred_2[i][0]=2
  else:
    y_pred_2[i][0]=1

In [23]:
y_pred_2

array([[1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [27]:
import csv
myList = []
header=['name','Loan Defaulted or Not']
for i in range(0,400):


   
    score = y_pred_2[i][0]
    row = [i+600,str(score)]
    myList.append(row)


with open('/content/Track_1 - Copy - Copy - Copy.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)

    # write the header
    writer.writerow(header)

    # write multiple rows
    writer.writerows(myList)